approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: true
author_approval: required
reviewers:
  members:
  - ckometter
  - zibrov-zlobin
  - mandolout
  - spanto
  - mserlin
  - cltschirhart
  name: pullapprove
  required: 2
