approve_by_comment: true
approve_regex: '^(Approved|:shipit:|:\+1:|LGTM|lgtm|Lgtm)'
reject_regex: ^Rejected
reset_on_push: true
author_approval: required
reviewers:
  members:
  - ckometter
  - zibrov-zlobin
  - mandolout
  - mserlin
  - cltschirhart
  name: pullapprove
  required: 2
